@host=https://localhost:7013
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTkxMTcwNi05MzdiLTRmMWMtOWE2MS1mYzQyM2RmM2FjOGMiLCJnaXZlbl9uYW1lIjoiQWxseXNzb24iLCJmYW1pbHlfbmFtZSI6IlNhbnRvcyIsImp0aSI6IjRlOGNhZDJjLTA0MjEtNGEwYS1hYzhkLTBmMzgxNTAxYWI0YiIsImV4cCI6MTY5NzgzOTA5MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.GsGUpSwLMW5NpHddui5sCR8uyQigxvk0k9mkRa4Llj4

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}
