@host=https://localhost:7013
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTMxZGY5YS1mZGJjLTQxZjMtYWNjYy00YTg4MDYxYWM1NDgiLCJnaXZlbl9uYW1lIjoiQWxseXNzb24iLCJmYW1pbHlfbmFtZSI6IlNhbnRvcyIsImp0aSI6IjQ2NDg4YmJkLTE0Y2ItNGYyNy05OTM4LWYyZmVjZjM2NjM4YSIsImV4cCI6MTY5Nzc1NjM2OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.TTMs55wILhj4L7fdo6YSeyjhHvIRlCh1-3WfqpMBKAs

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}
