@host=https://localhost:7013

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZDQxMDMxOC02NDA1LTRiZGItODE0MS0zYzgwMTg3MTA0ZGQiLCJnaXZlbl9uYW1lIjoiQWxseXNzb24iLCJmYW1pbHlfbmFtZSI6IlNhbnRvcyIsImp0aSI6ImRmN2YxNzJjLTY1ZDItNGQ0ZC1iYTQyLTIxNjZhYWMzMTg5MSIsImV4cCI6MTY5NzY4NTQ5MSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.96ZxELfuMJE8GeL-BDiHjS6fsFrrDtnIYBPKH0MJJo0
